/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.software;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Sam King
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pwTextFeild = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        signUpBtn = new javax.swing.JButton();
        cancleBtn = new javax.swing.JButton();
        unTextFeild = new javax.swing.JTextField();
        DD = new javax.swing.JTextField();
        pobTextFeild = new javax.swing.JTextField();
        genreComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        EXIT = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        MM = new javax.swing.JTextField();
        YYYY = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        musicList = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MMPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        jLabel2.setText("Date of Birth");

        jLabel3.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        jLabel3.setText("Place of Birth");

        pwTextFeild.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        pwTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwTextFeildActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("Georgia Pro Black", 0, 36)); // NOI18N
        jLabel5.setText("Signing up");

        signUpBtn.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        signUpBtn.setText("Sign up");
        signUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBtnActionPerformed(evt);
            }
        });

        cancleBtn.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        cancleBtn.setText("Cancel");
        cancleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleBtnActionPerformed(evt);
            }
        });

        unTextFeild.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        unTextFeild.setText("Enter Username Here");
        unTextFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UNCllicked(evt);
            }
        });
        unTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unTextFeildActionPerformed(evt);
            }
        });

        DD.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        DD.setText("DD");
        DD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DDClicked(evt);
            }
        });

        pobTextFeild.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        pobTextFeild.setText("Enter PoB Here");
        pobTextFeild.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PoBClicked(evt);
            }
        });
        pobTextFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pobTextFeildActionPerformed(evt);
            }
        });

        genreComboBox.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        genreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rock", "Indie", "Drum and Bass", "Country", "Pop", "Classical", "Jazz", "Metal", "Funk", "House", " " }));
        genreComboBox.setToolTipText("");
        genreComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        jLabel6.setText("Music Genre");

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        CLEAR.setText("RESET");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        MM.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        MM.setText("MM");
        MM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MMMouseClicked(evt);
            }
        });
        MM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MMActionPerformed(evt);
            }
        });

        YYYY.setFont(new java.awt.Font("Georgia Pro Black", 0, 18)); // NOI18N
        YYYY.setText("YYYY");
        YYYY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YYYYMouseClicked(evt);
            }
        });
        YYYY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YYYYActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        musicList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(signUpBtn)
                                .addGap(106, 106, 106)
                                .addComponent(cancleBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pobTextFeild, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwTextFeild, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 3, Short.MAX_VALUE)
                                .addComponent(unTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(musicList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CLEAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(EXIT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CLEAR)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(unTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(YYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addComponent(pobTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(pwTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(musicList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(signUpBtn)
                            .addComponent(cancleBtn))))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList <String> prefMusic = new ArrayList<>();
    private void signUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBtnActionPerformed
        // TODO add your handling code here:
        final int NUM_FIELDS = 7;
        int numCorrect = 0;
        String errorMessage = "";

        String username = "";
        int dateDay = 0;
        int dateMonth = 0;
        int dateYear = 0;
        String password = "";
        String birthplace = "";
        
       //validate username
       if(unTextFeild.getText().length() < 2 || username.length() > 25){
       errorMessage = errorMessage.concat("Username is to long/short. \n");
       } else{
           numCorrect++;
           username = unTextFeild.getText();
       }
       
   //validate Date of birth
       if(DD.getText().equalsIgnoreCase("DD") || DD.getText().isEmpty()){
       errorMessage = errorMessage.concat("Day feild is empty. \n");
    } else {
          //data is present
          try {//convert to int
              int dd = Integer.parseInt(DD.getText());
              if(dd <= 0 || dd>30){
                  errorMessage = errorMessage.concat("Invalid day. \n");
              } else {//all good
                  dateDay = dd;
                  numCorrect++;
              }
          } catch (NumberFormatException e){
              //not a number
              errorMessage = errorMessage.concat("Day is not a vald number. \n");
          }
       }
       
   //validate month of birth
       if(MM.getText().equalsIgnoreCase("MM") || MM.getText().isEmpty()){
       errorMessage = errorMessage.concat("Month feild is empty. \n");
    } else {
          //data is present
          try {//convert to int
              int mm = Integer.parseInt(MM.getText());
              if(mm <= 0 || mm>30){
                  errorMessage = errorMessage.concat("Invalid month. \n");
              } else {
                  dateMonth = mm;
                  numCorrect++;
              }
          } catch (NumberFormatException e){
              //not a number
              errorMessage = errorMessage.concat("Month is not a valid number. \n");
          }
       }
       //validate year of birth
       if(YYYY.getText().equalsIgnoreCase("YYYY") || YYYY.getText().isEmpty()){
       errorMessage = errorMessage.concat("Year feild is empty. \n");
    } else {//data is present
          try {//convert to int
              int yyyy = Integer.parseInt(MM.getText());
              if(yyyy <= 0 || yyyy>30){
                  errorMessage = errorMessage.concat("Invalid Year. \n");
              } else {
                  dateYear = yyyy;
                  numCorrect++;
              }
          } catch (NumberFormatException e){//not a real number
              errorMessage = errorMessage.concat("Year is not a valid number. \n");
          }
       }
       String date = DD.getText() + "/" + MM.getText() + "/" + YYYY.getText();
       
       
       //validate Birthplace
       if(pobTextFeild.getText().length() < 2 || pobTextFeild.getText().length() > 30){
        errorMessage = errorMessage.concat("Place of birth is to long/short. \n");
       } else{
           numCorrect++;
           birthplace = pobTextFeild.getText();
       }
       //validate password
       if(pwTextFeild.getText().length() < 2 || pwTextFeild.getText().length() > 25){
       errorMessage = errorMessage.concat("Password is to long/short. \n");
       } else{
           numCorrect++;
           password = pwTextFeild.getText();
       }
       
       if(prefMusic.size() < 1){
          errorMessage = errorMessage.concat("You must add music \n"); 
       } else{
           numCorrect++;
       }
       
       if(numCorrect < NUM_FIELDS)
       {    
          JOptionPane.showMessageDialog(new JPanel(), errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
       }else{
           
       
       //fill in the homies information
        Member newHomie = new Member();
        newHomie.userName = username;
        newHomie.dateOfBirth = date;
        newHomie.passWord = password;
        newHomie.placeOfBirth = birthplace;
        newHomie.prefMusic = prefMusic;
        new SocketCommunicator().signUp(newHomie);
        
        JOptionPane.showMessageDialog(new JPanel(), "Profile Created!", "Info", JOptionPane.INFORMATION_MESSAGE);
        
                        
        this.dispose();
        new Music(username).setVisible(true);
    }
    }//GEN-LAST:event_signUpBtnActionPerformed

    private void cancleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleBtnActionPerformed
        this.dispose();
        new UI().setVisible(true);
    }//GEN-LAST:event_cancleBtnActionPerformed

    private void unTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unTextFeildActionPerformed

    private void pobTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pobTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pobTextFeildActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
      System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        pobTextFeild.setText("  Enter date of birth here");
        unTextFeild.setText(" Enter username here");
        DD.setText("DD");
        MM.setText("MM");
        YYYY.setText("YYYY");
        pwTextFeild.setText("");
    }//GEN-LAST:event_CLEARActionPerformed

    private void pwTextFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwTextFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwTextFeildActionPerformed

    private void PoBClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PoBClicked
        // TODO add your handling code here:
        pobTextFeild.setText("");
    }//GEN-LAST:event_PoBClicked

    private void DDClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DDClicked
        // TODO add your handling code here:
        DD.setText("");
    }//GEN-LAST:event_DDClicked

    private void UNCllicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UNCllicked
        // TODO add your handling code here:
        unTextFeild.setText("");
    }//GEN-LAST:event_UNCllicked

    private void MMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMActionPerformed

    private void YYYYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YYYYActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_YYYYActionPerformed

    private void YYYYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YYYYMouseClicked
        // TODO add your handling code here:
        YYYY.setText("");
    }//GEN-LAST:event_YYYYMouseClicked

    private void MMPressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_MMPressed

    private void MMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMMouseClicked
        // TODO add your handling code here:
        MM.setText("");
    }//GEN-LAST:event_MMMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(genreComboBox.getSelectedIndex()!=-1){
            String item = genreComboBox.getSelectedItem().toString();
            prefMusic.add(item);
            musicList.add(item);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void musicListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_musicListActionPerformed

    private void genreComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLEAR;
    private javax.swing.JTextField DD;
    private javax.swing.JButton EXIT;
    private javax.swing.JTextField MM;
    private javax.swing.JTextField YYYY;
    private javax.swing.JButton cancleBtn;
    private javax.swing.JComboBox<String> genreComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private java.awt.List musicList;
    private javax.swing.JTextField pobTextFeild;
    private javax.swing.JPasswordField pwTextFeild;
    private javax.swing.JButton signUpBtn;
    private javax.swing.JTextField unTextFeild;
    // End of variables declaration//GEN-END:variables
}
