/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicnetworkserver;

import java.io.ObjectInputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.ArrayList;
import systems.software.Member;
import systems.software.Posts;
import systems.software.Songs;

/**
 *
 * @author LiamF
 */
public class MusicNetworkgui extends javax.swing.JFrame {

    //globals
    final private ArrayList<Member> member = new ArrayList<>();
    final private ArrayList<Posts> posts = new ArrayList<>();
    final private ArrayList<Songs> songs = new ArrayList<>();
    
    
    /**
     * Creates new form MusicNetworkgui
     */
    public MusicNetworkgui() {
        initComponents();
        Begin();
    }
    void Begin(){
        new Thread (this::signUp).start();
        
        new Thread (this::logIn).start();
        
        new Thread (this::postSend).start();
        
        new Thread (this::postReceive).start();
        
        new Thread (this::DBsave).start();
        
        new Thread (this::DBload).start();
        
        new Thread (this::songSend).start();
        
        new Thread (this::songReceive).start();
                
    }

    
    private void signUp() {
        while(true){
        try{
            ServerSocket socket = new ServerSocket(2222);
            Socket client = socket.accept();
            
            ObjectInputStream inputStream = new ObjectInputStream(client.getInputStream());
            Member receiveMember = (Member)inputStream.readObject();
            
            member.add(receiveMember);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
                
        }
    }
    private void logIn(){  
    }
    private void postSend(){
    }
    private void postReceive(){
    }
    private void DBsave(){
    }
    private void DBload(){
    }
    private void songSend(){
    }
    private void songReceive(){
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("button");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(121, 121, 121))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicNetworkgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicNetworkgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicNetworkgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicNetworkgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicNetworkgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
